# Задание
* Собрать информацию о всех строящихся объектах на сайте "наш.дом.рф"
* Cохранить ее в pandas dataframe
* Cохранить pandas dataframe в excel
* Cохранить pandas dataframe в pickle
* Cохранить pandas dataframe в БД

# Задание *
* Написать скрипт, который скачивает фотографии всех строящихся объектов с сайта "наш.дом.рф"

In [1]:
import requests
offset_ = 1
limit_ = 100
url = f'https://xn--80az8a.xn--d1aqf.xn--p1ai/%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D1%8B/api/kn/object?offset={offset_}&limit={limit_}&sortField=devId.devShortCleanNm&sortType=asc&objStatus=0'
res = requests.get(url)

In [2]:
import pandas as pd
data = pd.json_normalize(res.json().get('data').get('list'))  # df для начального списка с общей информацией
data = data.rename(columns={'objId':'id'})

print(data.shape)
data.head()

(100, 35)

,id,rpdRegionCd,objAddr,objFloorMin,objFloorMax,objElemLivingCnt,objReady100PercDt,objSquareLiving,objCompensFundFlg,objProblemFlg,...,developer.orgForm.fullForm,developer.orgForm.shortForm,developer.companyGroup,developer.devInn,objCommercNm,complexShortName,developer.bankruptStage.bankruptStageCd,developer.bankruptStage.bankruptStageDesc,developer.bankruptStage.bankruptLawUrl,developer.orgBankruptMsgDttm
0,13398,72,"г Тюмень, ул Профсоюзная, д. 56",7,10,43,2024-12-31,4812.98,0,0,...,Акционерное общество,АО,6.994210e+08,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
1,13383,72,г Тюмень,4,20,68,2022-06-30,6289.98,1,0,...,Акционерное общество,АО,6.994210e+08,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
2,13397,72,"г Тюмень, ул Профсоюзная, д. 56",6,12,65,2024-12-31,6248.51,0,0,...,Акционерное общество,АО,6.994210e+08,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
3,13391,72,"г Тюмень, ул Профсоюзная",3,12,44,2022-06-30,4293.67,1,0,...,Акционерное общество,АО,6.994210e+08,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
4,23682,47,д Агалатово,10,10,54,2022-06-30,2748.15,1,0,...,Общество с ограниченной ответственностью,ООО,5.562608e+09,7806536079,"Жилой комплекс ""84 высота""",NaN,NaN,NaN,NaN,NaN

In [3]:
new_data = pd.DataFrame() # df для детальной информации по каждому дому

ids = data['id']
for i in range(len(ids)):
    url = f'https://xn--80az8a.xn--d1aqf.xn--p1ai/%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D1%8B/api/object/{ids[i]}'
    res = requests.get(url)
    new_data = new_data.append(pd.json_normalize(res.json().get('data')))

print(new_data.shape)
new_data.head()

(100, 108)

,id,pdId,region,address,floorMin,floorMax,objElemLivingCnt,objReady100PercDt,wallMaterialShortDesc,objLkFinishTypeDesc,...,metro.time,metro.isWalk,metro.colors,greenAreaIndexValue,airQualityIndexValue,complexShortNm,developer.bankruptStage.bankruptStageCd,developer.bankruptStage.bankruptStageDesc,developer.bankruptStage.bankruptLawUrl,developer.orgBankruptMsgDttm
0,13398,28141,72,"г Тюмень, ул Профсоюзная, д. 56",7,10,43,2024-12-31,Другое,Без отделки,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,13383,28105,72,г Тюмень,4,20,68,2022-06-30,Другое,По желанию заказчика,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,13397,28141,72,"г Тюмень, ул Профсоюзная, д. 56",6,12,65,2024-12-31,Другое,Без отделки,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,13391,28101,72,"г Тюмень, ул Профсоюзная",3,12,44,2022-06-30,Другое,По желанию заказчика,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,23682,64486,47,д Агалатово,10,10,54,2022-06-30,Блоки,Без отделки,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
final_data = new_data.merge(data, on='id', how='left')
print(final_data.shape)
final_data.head()

(100, 142)

,id,pdId_x,region,address,floorMin,floorMax,objElemLivingCnt_x,objReady100PercDt_x,wallMaterialShortDesc,objLkFinishTypeDesc,...,developer.orgForm.fullForm_y,developer.orgForm.shortForm_y,developer.companyGroup,developer.devInn_y,objCommercNm,complexShortName,developer.bankruptStage.bankruptStageCd_y,developer.bankruptStage.bankruptStageDesc_y,developer.bankruptStage.bankruptLawUrl_y,developer.orgBankruptMsgDttm_y
0,13398,28141,72,"г Тюмень, ул Профсоюзная, д. 56",7,10,43,2024-12-31,Другое,Без отделки,...,Акционерное общество,АО,6.994210e+08,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
1,13383,28105,72,г Тюмень,4,20,68,2022-06-30,Другое,По желанию заказчика,...,Акционерное общество,АО,6.994210e+08,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
2,13397,28141,72,"г Тюмень, ул Профсоюзная, д. 56",6,12,65,2024-12-31,Другое,Без отделки,...,Акционерное общество,АО,6.994210e+08,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
3,13391,28101,72,"г Тюмень, ул Профсоюзная",3,12,44,2022-06-30,Другое,По желанию заказчика,...,Акционерное общество,АО,6.994210e+08,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
4,23682,64486,47,д Агалатово,10,10,54,2022-06-30,Блоки,Без отделки,...,Общество с ограниченной ответственностью,ООО,5.562608e+09,7806536079,"Жилой комплекс ""84 высота""",NaN,NaN,NaN,NaN,NaN

In [5]:
data.to_excel("total_data_1.xlsx")

In [6]:
final_data.to_pickle("total_data_1")

# Сохранение в BD

In [7]:
#Удалить
#В этих колонках содержатся массивы, приведем их к дополнительным столбцам в dataframe
# image_urls = final_data['photoRenderDTO'].copy()
# final_data['photoRenderDTO'] = final_data['photoRenderDTO'].astype(str)
# final_data['objectTransportInfo'] = final_data['objectTransportInfo'].astype(str)
# final_data['metro.colors'] = final_data['metro.colors'].astype(str)

## photoRenderDTO

In [7]:
def get_photoRenderDTO(column):
    """тк в некоторых полях таблицы хранится list(dict) надо привести эти поля к dataFrame"""
    ret = pd.DataFrame()
    for elem in column:
        for i in range(len(elem)):
            ret = ret.append(pd.DataFrame.from_records(data = elem[i], index=[1]))
    return ret

In [8]:
photoRenderDTO = get_photoRenderDTO(final_data['photoRenderDTO'])
photoRenderDTO = photoRenderDTO.rename(columns={'objId':'id'})
photoRenderDTO

,devId,knFlg,loadDttm,objBuildTypeShortDesc,id,objReadyDesc,objRenderPhotoDttm,objRenderPhotoHiddenFlg,objRenderPhotoNm,objRenderPhotoSize,objRenderPhotoUrl,ordNum,pdId,rpdId
1,306,1,02-05-2022 00:56,Жилое,13398,Строится,12-05-2021 16:52,0,IMG_20210512_093624.jpg,1325881,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,1,28141,585074
1,306,1,02-05-2022 00:56,Жилое,13398,Строится,12-05-2021 16:52,0,IMG_20210512_0936261.jpg,1383679,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,2,28141,585074
1,306,1,02-05-2022 00:56,Жилое,13398,Строится,17-09-2021 14:54,0,IMG_8196.JPG,101323,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,3,28141,585074
1,306,1,02-05-2022 00:56,Жилое,13398,Строится,17-09-2021 14:54,0,IMG_81971.JPG,80019,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,4,28141,585074
1,306,1,02-05-2022 00:56,Жилое,13398,Строится,20-01-2022 10:36,0,IMG_8924.JPG,322146,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,5,28141,585074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,7040,1,02-05-2022 00:56,Жилое,41616,Строится,08-07-2021 15:32,0,42.jpg,6076000,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,4,472265,587621
1,7040,1,02-05-2022 00:56,Жилое,41616,Строится,08-07-2021 15:32,0,73.jpg,4563822,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,5,472265,587621
1,7040,1,02-05-2022 00:56,Жилое,41616,Строится,08-07-2021 15:32,0,24.jpg,9506819,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,6,472265,587621
1,7040,1,02-05-2022 00:56,Жилое,41616,Строится,08-07-2021 15:32,0,35.jpg,9785939,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,7,472265,587621
1,7040,1,02-05-2022 00:56,Жилое,41616,Строится,08-07-2021 15:32,0,56.jpg,10272081,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,8,472265,587621

## objectTransportInfo

In [9]:
def get_dict(dictionary):
    """возвращает словарь листы которого заменены на строки с сепаратором ','"""
    ret = {}
    for k in dictionary.keys():
        if type(dictionary[k]) is list:
            ret[k] = ','.join([str(item) for item in dictionary[k]])
        else:
            ret[k] = str(dictionary[k])
    return ret

In [10]:
def get_objectTransportInfo(columns, column_name, id):
    """тк в некоторых полях таблицы хранится list(dict) надо привести эти поля к dataFrame.
    Кроме того необходимо добавить id к полученному DataFrame"""
    ret = pd.DataFrame()
    q = columns[column_name].copy()
    q[id] = columns[id]
    for i in range(len(columns)):
        for j in range(len(columns.iloc[i]['objectTransportInfo'])):
            z = get_dict(columns.iloc[i]['objectTransportInfo'][j])
            z['id'] = columns.iloc[i][id]
            ret = ret.append(pd.DataFrame.from_records(data = z, index=[1]))
    return ret

In [11]:
objectTransportInfo = get_objectTransportInfo(final_data[['objectTransportInfo','id']], 'objectTransportInfo', 'id')
objectTransportInfo

,id,isMetroStationDistWalking,metroLineColorHexCode,metroLineColorsHexCode,metroStationDistLength,metroStationDistTime,metroStationNm
1,44076,False,D80707,#D80707,0.229,10.9166666666667,Комсомольская
1,44076,False,D80707,#D80707,0.42,11.0833333333333,Кировская
1,44076,False,D80707,#D80707,0.756,12.6833333333333,Парк Культуры
1,27476,False,BAC8E8,#BAC8E8,1.74,33.0833333333333,Бунинская аллея
1,27476,False,BAC8E8,#BAC8E8,2.118,33.4166666666667,Бульвар Адмирала Ушакова
1,27476,False,E42313,#E42313,2.1,34.9166666666667,Ольховая
1,30292,True,CD0505,#CD0505,2.022,24.2666666666667,Аметьево
1,30292,False,CD0505,#CD0505,0.409,8.98333333333333,Горки
1,30292,False,CD0505,#CD0505,0.692,14.5833333333333,Проспект Победы
1,26503,True,CC4C6E,#CC4C6E,1.015,12.1666666666667,ЗИЛ
1,26503,True,CC4C6E,"#CC4C6E,#4FB04F",1.6,19.2,Автозаводская
1,26503,False,ADACAC,#ADACAC,0.815,13.2333333333333,Тульская
1,20524,True,4FB04F,#4FB04F,0.914,10.9666666666667,Водный стадион
1,20524,True,CC4C6E,#CC4C6E,1.014,12.1666666666667,Балтийская
1,20524,False,4FB04F,#4FB04F,0.577,10.9166666666667,Войковская
1,21720,True,4FB04F,#4FB04F,1.818,21.8166666666667,Беломорская
1,21720,False,4FB04F,#4FB04F,1.086,16.0333333333333,Речной вокзал
1,21720,False,4FB04F,#4FB04F,0.812,19.75,Водный стадион
1,45249,True,4FB04F,#4FB04F,1.755,21.05,Беломорская
1,45249,False,4FB04F,#4FB04F,1.023,15.9833333333333,Речной вокзал
1,45249,False,4FB04F,#4FB04F,0.71,17.4666666666667,Ховрино
1,33899,True,CD0505,#CD0505,1.412,16.95,Октябрьская
1,33899,False,CD0505,#CD0505,2.463,29.55,Речной вокзал
1,33899,False,CD0505,#CD0505,2.62,31.45,Площадь Ленина
1,44474,True,0A6F20,#0A6F20,1.697,20.3666666666667,Площадь Гарина-Михайловского
1,44474,False,CD0505,#CD0505,2.254,27.0333333333333,Площадь Ленина
1,44474,False,CD0505,#CD0505,2.915,34.9833333333333,Красный проспект
1,44489,True,0A6F20,#0A6F20,1.619,19.4333333333333,Площадь Гарина-Михайловского
1,44489,False,CD0505,#CD0505,2.264,27.1666666666667,Площадь Ленина
1,44489,False,CD0505,#CD0505,2.926,35.1166666666667,Красный проспект
1,44621,True,0A6F20,#0A6F20,1.705,20.4666666666667,Площадь Гарина-Михайловского
1,44621,False,CD0505,#CD0505,2.2,26.4,Площадь Ленина
1,44621,False,CD0505,#CD0505,2.86,34.3166666666667,Красный проспект

## MetroColors

In [12]:
def get_metroColors(column):
    """тк в некоторых полях таблицы хранится list(dict) надо привести эти поля к dataFrame"""
    ret = pd.DataFrame()
    for elem in column:
        for i in range(len(elem)):
            ret = ret.append(pd.DataFrame.from_records(data = elem[i], index=[1]))
    return ret

In [13]:
metroColors = get_metroColors(final_data['photoRenderDTO'])
metroColors = metroColors.rename(columns={'objId':'id'})
metroColors

,devId,knFlg,loadDttm,objBuildTypeShortDesc,id,objReadyDesc,objRenderPhotoDttm,objRenderPhotoHiddenFlg,objRenderPhotoNm,objRenderPhotoSize,objRenderPhotoUrl,ordNum,pdId,rpdId
1,306,1,02-05-2022 00:56,Жилое,13398,Строится,12-05-2021 16:52,0,IMG_20210512_093624.jpg,1325881,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,1,28141,585074
1,306,1,02-05-2022 00:56,Жилое,13398,Строится,12-05-2021 16:52,0,IMG_20210512_0936261.jpg,1383679,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,2,28141,585074
1,306,1,02-05-2022 00:56,Жилое,13398,Строится,17-09-2021 14:54,0,IMG_8196.JPG,101323,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,3,28141,585074
1,306,1,02-05-2022 00:56,Жилое,13398,Строится,17-09-2021 14:54,0,IMG_81971.JPG,80019,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,4,28141,585074
1,306,1,02-05-2022 00:56,Жилое,13398,Строится,20-01-2022 10:36,0,IMG_8924.JPG,322146,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,5,28141,585074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,7040,1,02-05-2022 00:56,Жилое,41616,Строится,08-07-2021 15:32,0,42.jpg,6076000,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,4,472265,587621
1,7040,1,02-05-2022 00:56,Жилое,41616,Строится,08-07-2021 15:32,0,73.jpg,4563822,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,5,472265,587621
1,7040,1,02-05-2022 00:56,Жилое,41616,Строится,08-07-2021 15:32,0,24.jpg,9506819,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,6,472265,587621
1,7040,1,02-05-2022 00:56,Жилое,41616,Строится,08-07-2021 15:32,0,35.jpg,9785939,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,7,472265,587621
1,7040,1,02-05-2022 00:56,Жилое,41616,Строится,08-07-2021 15:32,0,56.jpg,10272081,https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...,8,472265,587621

## Сохранение в sql

In [14]:
# Удаляем столбцы, которые мы обработали отдельно. Восстановить исходную запись можно будет по 'join table2 on table1.id = table2.id'
final_data = final_data.drop(columns=['photoRenderDTO', 'objectTransportInfo', 'metro.colors'])

In [15]:
import sqlite3

conn = sqlite3.connect("ASD")

final_data.to_sql("ASD", conn, if_exists='replace', index=False)
photoRenderDTO.to_sql('photoRenderDTO', conn, if_exists='replace', index=False)
objectTransportInfo.to_sql('objectTransportInfo', conn, if_exists='replace', index=False)
metroColors.to_sql('metroColors', conn, if_exists='replace', index=False)

conn.commit()
conn.close()

# Выгрузка картинок

* Написать скрипт, который скачивает фотографии всех строящихся объектов с сайта "наш.дом.рф"
Делаю для 10-ти тк очень долго ждать всей выгрузки

In [16]:
final_data['siteStatus'].unique()

array(['Строящиеся'], dtype=object)

In [20]:
import os

#Создаем папки для каждого объекта
for path in photoRenderDTO['id'].unique():
    if not os.path.exists(str(path)):
        os.mkdir(str(path))


#вкачиваем картинки в соответсвующую папку
k = 1
prevId = 0
for i, row in photoRenderDTO.iterrows():
    id = str(row['id'])
    if prevId != id:
        prevId = id
        k = 1
    url = row['objRenderPhotoUrl']
    p = requests.get(url)
    out = open(id + '/' + id + '_' + str(k) + '.jpg', 'wb')
    k = k + 1
    out.write(p.content)
    out.close()

In [17]:
#ВСё
counts = 10 #len(final_data)

In [32]:
import os
for j in range(counts):
    # if photoRenderDTO['objReadyDesc'] == 'Строится':
    #     k = 1
    #     # os.mkdir(str(photoRenderDTO['id']))
    for i in photoRenderDTO.items():
        print(i)
        print()
            # id = str(i['objId'])
            # p = requests.get(i['objRenderPhotoUrl'])
            # out = open(id + '/' + id + '_' + str(k) + '.jpg', 'wb')
            # k = k + 1
            # out.write(p.content)
            # out.close()

('devId', 1     306
1     306
1     306
1     306
1     306
     ...
1    7040
1    7040
1    7040
1    7040
1    7040
Name: devId, Length: 247, dtype: int64)

('knFlg', 1    1
1    1
1    1
1    1
1    1
    ..
1    1
1    1
1    1
1    1
1    1
Name: knFlg, Length: 247, dtype: int64)

('loadDttm', 1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
           ...
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
Name: loadDttm, Length: 247, dtype: object)

('objBuildTypeShortDesc', 1    Жилое
1    Жилое
1    Жилое
1    Жилое
1    Жилое
     ...
1    Жилое
1    Жилое
1    Жилое
1    Жилое
1    Жилое
Name: objBuildTypeShortDesc, Length: 247, dtype: object)

('id', 1    13398
1    13398
1    13398
1    13398
1    13398
     ...
1    41616
1    41616
1    41616
1    41616
1    41616
Name: id, Length: 247, dtype: int64)

('objReadyDesc', 1    Строится
1    Строится
1    Строится
1    Строится
1    Строится
       ...
1    Строится
1    Строится
1    Строится
1    Строится
1    Строится
Name: objReadyDesc, Length: 247, dtype: object)

('objRenderPhotoDttm', 1    12-05-2021 16:52
1    12-05-2021 16:52
1    17-09-2021 14:54
1    17-09-2021 14:54
1    20-01-2022 10:36
           ...
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
Name: objRenderPhotoDttm, Length: 247, dtype: object)

('objRenderPhotoHiddenFlg', 1    0
1    0
1    0
1    0
1    0
    ..
1    0
1    0
1    0
1    0
1    0
Name: objRenderPhotoHiddenFlg, Length: 247, dtype: int64)

('objRenderPhotoNm', 1     IMG_20210512_093624.jpg
1    IMG_20210512_0936261.jpg
1                IMG_8196.JPG
1               IMG_81971.JPG
1                IMG_8924.JPG
               ...
1                      42.jpg
1                      73.jpg
1                      24.jpg
1                      35.jpg
1                      56.jpg
Name: objRenderPhotoNm, Length: 247, dtype: object)

('objRenderPhotoSize', 1     1325881
1     1383679
1      101323
1       80019
1      322146
       ...
1     6076000
1     4563822
1     9506819
1     9785939
1    10272081
Name: objRenderPhotoSize, Length: 247, dtype: int64)

('objRenderPhotoUrl', 1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
                           ...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
Name: objRenderPhotoUrl, Length: 247, dtype: object)

('ordNum', 1    1
1    2
1    3
1    4
1    5
    ..
1    4
1    5
1    6
1    7
1    8
Name: ordNum, Length: 247, dtype: int64)

('pdId', 1     28141
1     28141
1     28141
1     28141
1     28141
      ...
1    472265
1    472265
1    472265
1    472265
1    472265
Name: pdId, Length: 247, dtype: int64)

('rpdId', 1    585074
1    585074
1    585074
1    585074
1    585074
      ...
1    587621
1    587621
1    587621
1    587621
1    587621
Name: rpdId, Length: 247, dtype: int64)

('devId', 1     306
1     306
1     306
1     306
1     306
     ...
1    7040
1    7040
1    7040
1    7040
1    7040
Name: devId, Length: 247, dtype: int64)

('knFlg', 1    1
1    1
1    1
1    1
1    1
    ..
1    1
1    1
1    1
1    1
1    1
Name: knFlg, Length: 247, dtype: int64)

('loadDttm', 1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
           ...
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
Name: loadDttm, Length: 247, dtype: object)

('objBuildTypeShortDesc', 1    Жилое
1    Жилое
1    Жилое
1    Жилое
1    Жилое
     ...
1    Жилое
1    Жилое
1    Жилое
1    Жилое
1    Жилое
Name: objBuildTypeShortDesc, Length: 247, dtype: object)

('id', 1    13398
1    13398
1    13398
1    13398
1    13398
     ...
1    41616
1    41616
1    41616
1    41616
1    41616
Name: id, Length: 247, dtype: int64)

('objReadyDesc', 1    Строится
1    Строится
1    Строится
1    Строится
1    Строится
       ...
1    Строится
1    Строится
1    Строится
1    Строится
1    Строится
Name: objReadyDesc, Length: 247, dtype: object)

('objRenderPhotoDttm', 1    12-05-2021 16:52
1    12-05-2021 16:52
1    17-09-2021 14:54
1    17-09-2021 14:54
1    20-01-2022 10:36
           ...
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
Name: objRenderPhotoDttm, Length: 247, dtype: object)

('objRenderPhotoHiddenFlg', 1    0
1    0
1    0
1    0
1    0
    ..
1    0
1    0
1    0
1    0
1    0
Name: objRenderPhotoHiddenFlg, Length: 247, dtype: int64)

('objRenderPhotoNm', 1     IMG_20210512_093624.jpg
1    IMG_20210512_0936261.jpg
1                IMG_8196.JPG
1               IMG_81971.JPG
1                IMG_8924.JPG
               ...
1                      42.jpg
1                      73.jpg
1                      24.jpg
1                      35.jpg
1                      56.jpg
Name: objRenderPhotoNm, Length: 247, dtype: object)

('objRenderPhotoSize', 1     1325881
1     1383679
1      101323
1       80019
1      322146
       ...
1     6076000
1     4563822
1     9506819
1     9785939
1    10272081
Name: objRenderPhotoSize, Length: 247, dtype: int64)

('objRenderPhotoUrl', 1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
                           ...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
Name: objRenderPhotoUrl, Length: 247, dtype: object)

('ordNum', 1    1
1    2
1    3
1    4
1    5
    ..
1    4
1    5
1    6
1    7
1    8
Name: ordNum, Length: 247, dtype: int64)

('pdId', 1     28141
1     28141
1     28141
1     28141
1     28141
      ...
1    472265
1    472265
1    472265
1    472265
1    472265
Name: pdId, Length: 247, dtype: int64)

('rpdId', 1    585074
1    585074
1    585074
1    585074
1    585074
      ...
1    587621
1    587621
1    587621
1    587621
1    587621
Name: rpdId, Length: 247, dtype: int64)

('devId', 1     306
1     306
1     306
1     306
1     306
     ...
1    7040
1    7040
1    7040
1    7040
1    7040
Name: devId, Length: 247, dtype: int64)

('knFlg', 1    1
1    1
1    1
1    1
1    1
    ..
1    1
1    1
1    1
1    1
1    1
Name: knFlg, Length: 247, dtype: int64)

('loadDttm', 1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
           ...
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
Name: loadDttm, Length: 247, dtype: object)

('objBuildTypeShortDesc', 1    Жилое
1    Жилое
1    Жилое
1    Жилое
1    Жилое
     ...
1    Жилое
1    Жилое
1    Жилое
1    Жилое
1    Жилое
Name: objBuildTypeShortDesc, Length: 247, dtype: object)

('id', 1    13398
1    13398
1    13398
1    13398
1    13398
     ...
1    41616
1    41616
1    41616
1    41616
1    41616
Name: id, Length: 247, dtype: int64)

('objReadyDesc', 1    Строится
1    Строится
1    Строится
1    Строится
1    Строится
       ...
1    Строится
1    Строится
1    Строится
1    Строится
1    Строится
Name: objReadyDesc, Length: 247, dtype: object)

('objRenderPhotoDttm', 1    12-05-2021 16:52
1    12-05-2021 16:52
1    17-09-2021 14:54
1    17-09-2021 14:54
1    20-01-2022 10:36
           ...
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
Name: objRenderPhotoDttm, Length: 247, dtype: object)

('objRenderPhotoHiddenFlg', 1    0
1    0
1    0
1    0
1    0
    ..
1    0
1    0
1    0
1    0
1    0
Name: objRenderPhotoHiddenFlg, Length: 247, dtype: int64)

('objRenderPhotoNm', 1     IMG_20210512_093624.jpg
1    IMG_20210512_0936261.jpg
1                IMG_8196.JPG
1               IMG_81971.JPG
1                IMG_8924.JPG
               ...
1                      42.jpg
1                      73.jpg
1                      24.jpg
1                      35.jpg
1                      56.jpg
Name: objRenderPhotoNm, Length: 247, dtype: object)

('objRenderPhotoSize', 1     1325881
1     1383679
1      101323
1       80019
1      322146
       ...
1     6076000
1     4563822
1     9506819
1     9785939
1    10272081
Name: objRenderPhotoSize, Length: 247, dtype: int64)

('objRenderPhotoUrl', 1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
                           ...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
Name: objRenderPhotoUrl, Length: 247, dtype: object)

('ordNum', 1    1
1    2
1    3
1    4
1    5
    ..
1    4
1    5
1    6
1    7
1    8
Name: ordNum, Length: 247, dtype: int64)

('pdId', 1     28141
1     28141
1     28141
1     28141
1     28141
      ...
1    472265
1    472265
1    472265
1    472265
1    472265
Name: pdId, Length: 247, dtype: int64)

('rpdId', 1    585074
1    585074
1    585074
1    585074
1    585074
      ...
1    587621
1    587621
1    587621
1    587621
1    587621
Name: rpdId, Length: 247, dtype: int64)

('devId', 1     306
1     306
1     306
1     306
1     306
     ...
1    7040
1    7040
1    7040
1    7040
1    7040
Name: devId, Length: 247, dtype: int64)

('knFlg', 1    1
1    1
1    1
1    1
1    1
    ..
1    1
1    1
1    1
1    1
1    1
Name: knFlg, Length: 247, dtype: int64)

('loadDttm', 1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
           ...
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
Name: loadDttm, Length: 247, dtype: object)

('objBuildTypeShortDesc', 1    Жилое
1    Жилое
1    Жилое
1    Жилое
1    Жилое
     ...
1    Жилое
1    Жилое
1    Жилое
1    Жилое
1    Жилое
Name: objBuildTypeShortDesc, Length: 247, dtype: object)

('id', 1    13398
1    13398
1    13398
1    13398
1    13398
     ...
1    41616
1    41616
1    41616
1    41616
1    41616
Name: id, Length: 247, dtype: int64)

('objReadyDesc', 1    Строится
1    Строится
1    Строится
1    Строится
1    Строится
       ...
1    Строится
1    Строится
1    Строится
1    Строится
1    Строится
Name: objReadyDesc, Length: 247, dtype: object)

('objRenderPhotoDttm', 1    12-05-2021 16:52
1    12-05-2021 16:52
1    17-09-2021 14:54
1    17-09-2021 14:54
1    20-01-2022 10:36
           ...
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
Name: objRenderPhotoDttm, Length: 247, dtype: object)

('objRenderPhotoHiddenFlg', 1    0
1    0
1    0
1    0
1    0
    ..
1    0
1    0
1    0
1    0
1    0
Name: objRenderPhotoHiddenFlg, Length: 247, dtype: int64)

('objRenderPhotoNm', 1     IMG_20210512_093624.jpg
1    IMG_20210512_0936261.jpg
1                IMG_8196.JPG
1               IMG_81971.JPG
1                IMG_8924.JPG
               ...
1                      42.jpg
1                      73.jpg
1                      24.jpg
1                      35.jpg
1                      56.jpg
Name: objRenderPhotoNm, Length: 247, dtype: object)

('objRenderPhotoSize', 1     1325881
1     1383679
1      101323
1       80019
1      322146
       ...
1     6076000
1     4563822
1     9506819
1     9785939
1    10272081
Name: objRenderPhotoSize, Length: 247, dtype: int64)

('objRenderPhotoUrl', 1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
                           ...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
Name: objRenderPhotoUrl, Length: 247, dtype: object)

('ordNum', 1    1
1    2
1    3
1    4
1    5
    ..
1    4
1    5
1    6
1    7
1    8
Name: ordNum, Length: 247, dtype: int64)

('pdId', 1     28141
1     28141
1     28141
1     28141
1     28141
      ...
1    472265
1    472265
1    472265
1    472265
1    472265
Name: pdId, Length: 247, dtype: int64)

('rpdId', 1    585074
1    585074
1    585074
1    585074
1    585074
      ...
1    587621
1    587621
1    587621
1    587621
1    587621
Name: rpdId, Length: 247, dtype: int64)

('devId', 1     306
1     306
1     306
1     306
1     306
     ...
1    7040
1    7040
1    7040
1    7040
1    7040
Name: devId, Length: 247, dtype: int64)

('knFlg', 1    1
1    1
1    1
1    1
1    1
    ..
1    1
1    1
1    1
1    1
1    1
Name: knFlg, Length: 247, dtype: int64)

('loadDttm', 1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
           ...
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
Name: loadDttm, Length: 247, dtype: object)

('objBuildTypeShortDesc', 1    Жилое
1    Жилое
1    Жилое
1    Жилое
1    Жилое
     ...
1    Жилое
1    Жилое
1    Жилое
1    Жилое
1    Жилое
Name: objBuildTypeShortDesc, Length: 247, dtype: object)

('id', 1    13398
1    13398
1    13398
1    13398
1    13398
     ...
1    41616
1    41616
1    41616
1    41616
1    41616
Name: id, Length: 247, dtype: int64)

('objReadyDesc', 1    Строится
1    Строится
1    Строится
1    Строится
1    Строится
       ...
1    Строится
1    Строится
1    Строится
1    Строится
1    Строится
Name: objReadyDesc, Length: 247, dtype: object)

('objRenderPhotoDttm', 1    12-05-2021 16:52
1    12-05-2021 16:52
1    17-09-2021 14:54
1    17-09-2021 14:54
1    20-01-2022 10:36
           ...
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
Name: objRenderPhotoDttm, Length: 247, dtype: object)

('objRenderPhotoHiddenFlg', 1    0
1    0
1    0
1    0
1    0
    ..
1    0
1    0
1    0
1    0
1    0
Name: objRenderPhotoHiddenFlg, Length: 247, dtype: int64)

('objRenderPhotoNm', 1     IMG_20210512_093624.jpg
1    IMG_20210512_0936261.jpg
1                IMG_8196.JPG
1               IMG_81971.JPG
1                IMG_8924.JPG
               ...
1                      42.jpg
1                      73.jpg
1                      24.jpg
1                      35.jpg
1                      56.jpg
Name: objRenderPhotoNm, Length: 247, dtype: object)

('objRenderPhotoSize', 1     1325881
1     1383679
1      101323
1       80019
1      322146
       ...
1     6076000
1     4563822
1     9506819
1     9785939
1    10272081
Name: objRenderPhotoSize, Length: 247, dtype: int64)

('objRenderPhotoUrl', 1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
                           ...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
Name: objRenderPhotoUrl, Length: 247, dtype: object)

('ordNum', 1    1
1    2
1    3
1    4
1    5
    ..
1    4
1    5
1    6
1    7
1    8
Name: ordNum, Length: 247, dtype: int64)

('pdId', 1     28141
1     28141
1     28141
1     28141
1     28141
      ...
1    472265
1    472265
1    472265
1    472265
1    472265
Name: pdId, Length: 247, dtype: int64)

('rpdId', 1    585074
1    585074
1    585074
1    585074
1    585074
      ...
1    587621
1    587621
1    587621
1    587621
1    587621
Name: rpdId, Length: 247, dtype: int64)

('devId', 1     306
1     306
1     306
1     306
1     306
     ...
1    7040
1    7040
1    7040
1    7040
1    7040
Name: devId, Length: 247, dtype: int64)

('knFlg', 1    1
1    1
1    1
1    1
1    1
    ..
1    1
1    1
1    1
1    1
1    1
Name: knFlg, Length: 247, dtype: int64)

('loadDttm', 1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
           ...
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
1    02-05-2022 00:56
Name: loadDttm, Length: 247, dtype: object)

('objBuildTypeShortDesc', 1    Жилое
1    Жилое
1    Жилое
1    Жилое
1    Жилое
     ...
1    Жилое
1    Жилое
1    Жилое
1    Жилое
1    Жилое
Name: objBuildTypeShortDesc, Length: 247, dtype: object)

('id', 1    13398
1    13398
1    13398
1    13398
1    13398
     ...
1    41616
1    41616
1    41616
1    41616
1    41616
Name: id, Length: 247, dtype: int64)

('objReadyDesc', 1    Строится
1    Строится
1    Строится
1    Строится
1    Строится
       ...
1    Строится
1    Строится
1    Строится
1    Строится
1    Строится
Name: objReadyDesc, Length: 247, dtype: object)

('objRenderPhotoDttm', 1    12-05-2021 16:52
1    12-05-2021 16:52
1    17-09-2021 14:54
1    17-09-2021 14:54
1    20-01-2022 10:36
           ...
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
1    08-07-2021 15:32
Name: objRenderPhotoDttm, Length: 247, dtype: object)

('objRenderPhotoHiddenFlg', 1    0
1    0
1    0
1    0
1    0
    ..
1    0
1    0
1    0
1    0
1    0
Name: objRenderPhotoHiddenFlg, Length: 247, dtype: int64)

('objRenderPhotoNm', 1     IMG_20210512_093624.jpg
1    IMG_20210512_0936261.jpg
1                IMG_8196.JPG
1               IMG_81971.JPG
1                IMG_8924.JPG
               ...
1                      42.jpg
1                      73.jpg
1                      24.jpg
1                      35.jpg
1                      56.jpg
Name: objRenderPhotoNm, Length: 247, dtype: object)

('objRenderPhotoSize', 1     1325881
1     1383679
1      101323
1       80019
1      322146
       ...
1     6076000
1     4563822
1     9506819
1     9785939
1    10272081
Name: objRenderPhotoSize, Length: 247, dtype: int64)

('objRenderPhotoUrl', 1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
                           ...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
1    https://xn--80az8a.xn--d1aqf.xn--p1ai/api/ext/...
Name: objRenderPhotoUrl, Length: 247, dtype: object)

('ordNum', 1    1
1    2

In [43]:
counts = 10

In [59]:
for i in photoRenderDTO['id'].unique():
    print(i)

13398
13383
13397
13391
23682
36321
36912
44076
23494
27476
10891
39174
39176
39175
27049
41421
33928
41420
30292
18363
19457
18709
18708
21535
21534
21537
21536
39319
41625
41624
26503
42192
27542
26903
20524
29184
27779
24093
32811
32819
32836
32829
32815
27802
32843
32827
32820
23862
23863
27807
32838
32818
32837
32825
27803
27806
32839
32840
32841
32814
32831
32830
32835
32826
32813
32833
32817
32824
27808
27801
32823
32842
32832
32816
32834
32828
27798
32812
23864
21720
45249
33899
17712
17707
33745
44474
44489
44621
15888
15886
15889
15885
15891
15890
37264
45256
24820
24823
41618
41616

In [73]:
photoRenderDTO['objReadyDesc'].unique()

array(['Строится'], dtype=object)